# Generated by Django 4.0.2 on 2022-02-22 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='home_slug',
        ),
        migrations.AddField(
            model_name='blog',
            name='post_author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='post_date',
            field=models.CharField(help_text='yyyy.mm.dd', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='post_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
