# Generated by Django 4.0.2 on 2022-02-16 19:14

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_first_paragrapher',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_profile_image',
            field=models.ForeignKey(help_text='Vertical profile image 3x2 aspect ratio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_second_paragrapher',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_third_paragrapher',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title_skills_subsection',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_bg_img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_get_in_touch',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_paragrapher',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_send_a_message',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_send_button',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_background_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_github_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_lead_text',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_linkedin_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_typed_text',
            field=models.CharField(help_text='Typed text, separate words with commas (,)', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='work_lead_text',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='work_title',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.CreateModel(
            name='SkillLogos',
            fields=[
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
