# Generated by Django 4.0.2 on 2022-02-17 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('home_slug', models.CharField(max_length=50, null=True)),
                ('project_info', models.CharField(max_length=50, null=True)),
                ('category_title', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('client_title', models.CharField(blank=True, max_length=50)),
                ('client', models.CharField(blank=True, max_length=50)),
                ('project_date_title', models.CharField(max_length=50, null=True)),
                ('project_date', models.CharField(max_length=50)),
                ('project_url_title', models.CharField(blank=True, max_length=50)),
                ('project_url', models.URLField(blank=True, max_length=50)),
                ('website_button', models.CharField(blank=True, max_length=50)),
                ('website_button_url', models.URLField(blank=True, max_length=50)),
                ('github_button', models.CharField(blank=True, max_length=50)),
                ('github_button_url', models.URLField(blank=True, max_length=50)),
                ('banner_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('cover_image_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
