# Generated by Django 4.0.2 on 2022-02-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_portfoliosettings_blogsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footersettings',
            old_name='footer',
            new_name='copyright',
        ),
        migrations.AddField(
            model_name='footersettings',
            name='year',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
