# Generated by Django 4.0.3 on 2022-03-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_navbarsettings_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersettings',
            name='year',
        ),
    ]
